version: "3.9"

services:
  nginx:
    image: nginx:1.22.1
    ports:
      - "80:80"
      - "443:443"
    restart: "always"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certbot_etc:/etc/letsencrypt

  certbot:
    image: certbot/dns-cloudflare:v1.32.0
    volumes:
      - ./certbot_etc:/etc/letsencrypt
      - ./cloudflare.ini:/root/cloudflare.ini
    command: >-
      certonly --dns-cloudflare
      --dns-cloudflare-credentials /root/cloudflare.ini
      --dns-cloudflare-propagation-seconds 15
      --email garryiv@gmail.com
      --agree-tos --no-eff-email
      --force-renewal
      -d garryiv.com
      -d *.garryiv.com
